//Kyle Riedemann
//1-12-2015

/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/

public class EulerProblem02 {
	public static void main(String[] args) {

		long last = 1;
  		long beforeLast = 0;
  		long result = 0;
  		long sum = 0;

  		while(result < 4000000) {

	    	result = last + beforeLast;

	    	if (result > 4000000) break;

	    	beforeLast = last;
	    	last = result;

	    	if (result % 2 == 0) sum += result;
    	}

    	System.out.println("Sum of even numbers in the Fibbonacci sequence is " + sum);
	}
}
